version: 2
jobs:
  build:
    working_directory: ~/etcd4j-v3
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - setup_remote_docker
      - checkout
      - run: ./mvnw -Pdocker install
      - store_test_results:
          path: target/failsafe-reports